- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Grafana GPG key
  # GPG Keys are signatures which ensure that the packages installed are not tampered with
  # Without this key apt would decline the repository
  shell: |
    wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg
  args:
    creates: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present

- name: Install Grafana
  apt:
    name: "grafana={{ grafana_version }}"
    state: present
    update_cache: yes

- name: Configure Grafana root URL
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;?root_url'
    line: 'root_url = http://192.168.1.22:3000'
  notify: Restart Grafana

- name: Enable and start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started
    daemon_reload: yes
