all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/ansible_key

  children:
    debian:
      hosts:
        paperless:
          ansible_host: 192.168.1.12
        sabnzbd:
          ansible_host: 192.168.1.13
        prowlarr:
          ansible_host: 192.168.1.14
        sonarr:
          ansible_host: 192.168.1.15
        radarr:
          ansible_host: 192.168.1.16
        bazarr:
          ansible_host: 192.168.1.18
    ubuntu:
      hosts:
        jellyfin:
          ansible_host: 192.168.1.17
    ungrouped:
      hosts:
        localhost:
          ansible_connection: local
