all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/ansible_key

  children:
    documents:
      hosts:
        paperless:
          ansible_host: 192.168.1.12
    media:
      hosts:
        sabnzbd:
          ansible_host: 192.168.1.13
        prowlarr:
          ansible_host: 192.168.1.14
        sonarr:
          ansible_host: 192.168.1.15
        radarr:
          ansible_host: 192.168.1.16
        jellyfin:
          ansible_host: 192.168.1.17
        bazarr:
          ansible_host: 192.168.1.18
    monitoring:
      hosts:
        prometheus:
          ansible_host: 192.168.1.21
        grafana:
          ansible_host: 192.168.1.22
    kubernetes:
      hosts:
        k8smaster:
          ansible_host: 192.168.1.80
        k8sworker1:
          ansible_host: 192.168.1.81
        k8sworker2:
          ansible_host: 192.168.1.82
    cicd:
      hosts:
        github-runner:
          ansible_host: 192.168.1.23
    ungrouped:
      hosts:
        localhost:
          ansible_connection: local
