name: Ansible Syntax Checking

on:
  push:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create vault password file
        run: echo -n "${{ secrets.VAULT_PASSWORD }}" > /root/.vault_pass && chmod 600 /root/.vault_pass

      - name: Run Ansible syntax check
        run: |
          cd $GITHUB_WORKSPACE
          for playbook in playbooks/*.yml; do
            echo "Checking $playbook..."
            ansible-playbook "$playbook" --syntax-check
          done

      - name: Remove vault password file
        run: rm /root/.vault_pass
        if: always()

